name: CodeCov

on:
  pull_request:
    branches: [ main ]

jobs:
  cd:
    name: CodeCov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.23
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: |
          go test ./... ./modules/config/... ./modules/identity/... -coverprofile cover.out -coverpkg ./... ./modules/config/... ./modules/identity/...
